spring:
  boot:
    admin:
#      context-path: ${ADMIN_CONTEXTPATH:/admin}
      ui:
        brand: <img src="assets/img/10370-icon-service-Azure-Spring-Apps.svg"><span>Azure Spring Apps Admin</span>
        title: Azure Spring Apps Admin
        theme:
          background-enabled: false
          color: "#0078D4"
        external-views:
          - label: Azure Spring Apps
            url: https://learn.microsoft.com/azure/spring-apps/overview
        favicon: assets/img/azure-favicon.png
        favicon-danger: assets/img/azure-favicon.png
        login-icon: assets/img/10370-icon-service-Azure-Spring-Apps.svg
  cloud:
    azure:
      active-directory:
        enabled: true
#        redirect-uri-template: "{baseUrl}${spring.boot.admin.context-path}/login/oauth2/code/"
        credential:
          client-id: ${AAD_CLIENT_ID}
          client-secret: ${AAD_CLIENT_SECRET}
          profile:
            tenant-id: ${AAD_TENANT_ID}
      admin:
        fully-qualified-domain-name: ${FULLY_QUALIFIED_DOMAIN_NAME:http://localhost:8080}

  thymeleaf:
    check-template-location: false
  application:
    name: asa-spring-boot-admin-server

eureka:
  instance:
    # Set true to the consumption plan instance, set false to the standard plan.
    secure-port-enabled: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: info,health
