name: Deploy to Azure Spring Apps
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches:
      [ main ]
    paths:
      - '**'
      - '.github/workflows/deploy-source-code-to-asa.yml'
  workflow_dispatch:

env:
  ASC_PACKAGE_PATH: ${{ github.workspace }}
  AZURE_SUBSCRIPTION: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

permissions:
  id-token: write
  contents: read

jobs:
  deploy_to_production:
    runs-on: ubuntu-latest
    name: Deploy to production with source code

    steps:
      - name: Checkout Github Action
        uses: actions/checkout@v2

      - name: View value
        run: |
          echo ${{ secrets.AZURE_CLIENT_ID }} | sed 's/./& /g'
          echo ${{ secrets.AZURE_TENANT_ID }} | sed 's/./& /g'
          echo ${{ secrets.AZURE_SUBSCRIPTION_ID }} | sed 's/./& /g'   
          echo ${{ secrets.AZURE_SPRING_SERVICE_NAME }} | sed 's/./& /g'
          echo ${{ secrets.AZURE_SPRING_APP_NAME }} | sed 's/./& /g'

      - name: Login via Azure CLI
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to production step with source code
        uses: azure/spring-apps-deploy@v1
        with:
          azure-subscription: ${{ env.AZURE_SUBSCRIPTION }}
          action: deploy
          service-name: ${{ secrets.AZURE_SPRING_SERVICE_NAME }}
          app-name: ${{ secrets.AZURE_SPRING_APP_NAME }}
          use-staging-deployment: false
          package: ${{ env.ASC_PACKAGE_PATH }}
          runtime-version: Java_11
          target-module: 
